version: "3.8"

services:
  client:
    build:
      context: ./client
    command: npm run start
    container_name: client
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules